name: Ubuntu Linux Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:    
      matrix:
        arch: [32, 64]
    
    steps:
    - uses: actions/checkout@v1
    - name: Install deps
      run: sudo apt-get install indent
    - name: make format
      run: |
        make format 
        git diff
        ! git status -s | grep "^ M "
            
