name: Code Formatting

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:    
      matrix:
        arch: [64]
    
    steps:
    - uses: actions/checkout@v1
    - name: formatting
      run: make test-format
            
